### ISSUE TITLE
STA cannot save settings or game progress

### ISSUE THREAD

**Issue by retcinder** [supertuxadvance/org.sta.supertux-advance#1]
Gotta figure out how to do this.

**Comment by retcinder** [comment]
Ok, gotta make changes to STA upstream

**Comment by retcinder** [comment]
Actually, I'll just request for PhysFS support

**Comment by retcinder** [comment]
Temporary workaround made in latest commit.

**Comment by KelvinShadewing** [comment]
Um, care to elaborate? Saves are working fine for me.

**Comment by retcinder** [comment]
@KelvinShadewing flatpak directory nonsense (STA's flatpak is stored in a way that makes it's directory read only)
